[project]
name = "revenuebase-mcp-server"
version = "0.1.0"
description = "Revenuebase MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.18",
    "aiolimiter>=1.2.1",
    "fastmcp>=2.2.0",
    "requests>=2.32.3",
]
